replicaCount: 2
image: "nginx:latest"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

autoscaling:
  enabled: true
  type: cpu
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP
  name: http
