grafana:
  adminPassword: "${GRAFANA_ADMIN_PASSWORD}"
  service:
    type: LoadBalancer
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 6417
        revision: 1
        datasource: Prometheus

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true

serviceMonitor:
  enabled: true